### ISSUE TITLE
Bug when requesting help when asking help for the gamble command

### ISSUE THREAD

**Issue by MetaByte149** [Mrjamy/KonekoBot#32]
**Describe the bug**
When typing "$help gamble" the bot says :nekko: instead of an emote.

**To Reproduce**
Type "$help gamble" in a guild where the bot is active.

**Expected behavior**
The bot should display the nekko emote.

**Screenshots**
$help gamble

**Comment by Mrjamy** [comment]
I doubt this would be possible to fix in a nice and easy way as the output for the help command is generated from the commands docstring.

**Comment by Mrjamy** [comment]
Should be fixed now, will be deployed later.

**Comment by Mrjamy** [comment]
Issue is solved and deployed.
